export class AppConstants {
  /**
   * App Version
   */
  static readonly VERSION: string = '1.5.5'
  /**
   * App Version Code
   */
  static readonly VERSIONCODE: number = 10550
  /**
   * Version Description
   */
  static readonly VER_DESC: string = ''
  /**
   * AppGallery BundleName
   */
  static readonly BUNDLE_NAME_AG: string = 'cc.chenlvin.cloudmusic'
  /**
   * Git BundleName
   */
  static readonly BUNDLE_NAME_GIT: string = 'cn.chenlvin.melotopia.hm'
}